services:
  qbittorrent-port-helper:
        image: tyzen9/qbittorrent-port-helper:latest
        container_name: qbittorrent-port-helper
        restart: always
        volumes:
            # the "vpn-data" volume should be a shared volume with the VPN container
            # that writes a port.dat file in the root of this container containing
            # the dynamically assigned forwarded port number
            - vpn-data:/vpn-data 
        environment:
            - TZ_ID=${TZ_ID}
            - QBITTORRENT_USERNAME=${QBITTORRENT_USERNAME}
            - QBITTORRENT_PASSWORD=${QBITTORRENT_PASSWORD}
            - QBITTORRENT_PORT_NUMBER=${QBITTORRENT_PORT_NUMBER}
            - QBITTORRENT_URL=${QBITTORRENT_URL}
            # Optional Settings
            # - VPN_DATA_FILEPATH=${VPN_DATA_FILEPATH}
            # - WATCH_INTERVAL=${WATCH_INTERVAL}
            # - STARTUP_DELAY=${STARTUP_DELAY}
            # - LOG_LEVEL=${LOG_LEVEL}

volumes:
  vpn-data: