services:
  helper:
    build:
      context: .
    container_name: qbittorrent_port_helper
    # In development, we need these volumes to make changes live to the script
    volumes:
      - ./app:/usr/src/app/qph
      - ./pia-shared:/pia-shared
    environment:
      - QBITTORRENT_USERNAME=admin
      - QBITTORRENT_PASSWORD=abcd1234
      - QBITTORRENT_PORT_NUMBER=8080
      - QBITTORRENT_URL=http://qbittorrent
      # Optional settings, these are the defaults
      - FILE=/pia-shared/port.dat
      - WATCH_INTERVAL=30
    networks:
      - test-net

  # We light up an instance of qBittorrent just for development purposes
  # This will allow us to test connectivity to the qBittorrent API to make changes
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
    ports:
      - 8080:8080
    volumes:
      - qbt-config:/config
    restart: unless-stopped
    networks:
      - test-net      

networks:
  test-net:
    driver: bridge

volumes:
  qbt-config: