services:
  app:
    build:
      context: ..  # The build takes place one directory above .devcontainer
      dockerfile: .devcontainer/Dockerfile # but use the Dockerfile in this directory
    env_file:
      - ./.env # use the .env file in this location
    volumes:
      - ..:/workspace:cached
      - ../vpn-data:/vpn-data
    command: sleep infinity # Keeps the container alive during development (for shell access)
    networks:
      - dev-network

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=${QBITTORRENT_PORT_NUMBER}
    ports:
      - "${QBITTORRENT_PORT_NUMBER}:8080" # Map host port to container's WEBUI_PORT
      - "6881:6881" # Torrent traffic (TCP)
      - "6881:6881/udp" # Torrent traffic (UDP)
    volumes:
      - qbittorrent-config:/config
      - downloads:/downloads
    restart: unless-stopped
    networks:
      - dev-network

volumes:
  qbittorrent-config:
  downloads:

networks:
  dev-network:
    driver: bridge